### ISSUE TITLE
Liste des composants / Soudure ?

### ISSUE THREAD

**Issue by fonzarely** [DevFloor/minitel#5]
Hello,

Avons nous toute la liste des composants ? 
Que manque t til à faire ?

@++

**Comment by revolunet** [comment]
yes tous les composants sont là et soudés.

`ras❑❑e❑❑y p❑ l❑❑in` s'affiche à l'écran

je reste bloqué sur ce problème de caracteres qui ne passent pas.
Je pense qu'il faut verifier le circuit.

aussi je ne suis pas sur que toutes les touches du clavier marchent, il faut trouver un moyen de tester ca

**Comment by fonzarely** [comment]
Super, on se cale un rdv pour ça. En semaine prochaine si tu es dispo.
